#!/usr/bin/env bash
# LuCI 展示、菜单和前端相关修正。

set_build_signature() {
    local file="$BUILD_DIR/feeds/luci/modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/10_system.js"
    if [ -d "$(dirname "$file")" ] && [ -f $file ]; then
        sed -i "s/(\(luciversion || ''\))/(\1) + (' \/ build by ZqinKing')/g" "$file"
    fi
}

update_menu_location() {
    local samba4_path="$BUILD_DIR/feeds/luci/applications/luci-app-samba4/root/usr/share/luci/menu.d/luci-app-samba4.json"
    if [ -d "$(dirname "$samba4_path")" ] && [ -f "$samba4_path" ]; then
        sed -i 's/nas/services/g' "$samba4_path"
    fi

    local tailscale_path="$(get_custom_feed_worktree_dir)/luci-app-tailscale/root/usr/share/luci/menu.d/luci-app-tailscale.json"
    if [ -d "$(dirname "$tailscale_path")" ] && [ -f "$tailscale_path" ]; then
        sed -i 's/services/vpn/g' "$tailscale_path"
    fi
}


update_nginx_ubus_module() {
    local makefile_path="$BUILD_DIR/feeds/packages/net/nginx/Makefile"
    local source_date="2024-03-02"
    local source_version="564fa3e9c2b04ea298ea659b793480415da26415"
    local mirror_hash="92c9ab94d88a2fe8d7d1e8a15d15cfc4d529fdc357ed96d22b65d5da3dd24d7f"

    if [ -f "$makefile_path" ]; then
        sed -i "s/SOURCE_DATE:=2020-09-06/SOURCE_DATE:=$source_date/g" "$makefile_path"
        sed -i "s/SOURCE_VERSION:=b2d7260dcb428b2fb65540edb28d7538602b4a26/SOURCE_VERSION:=$source_version/g" "$makefile_path"
        sed -i "s/MIRROR_HASH:=515bb9d355ad80916f594046a45c190a68fb6554d6795a54ca15cab8bdd12fda/MIRROR_HASH:=$mirror_hash/g" "$makefile_path"
        echo "已更新 nginx-mod-ubus 模块的 SOURCE_DATE, SOURCE_VERSION 和 MIRROR_HASH。"
    else
        echo "错误：未找到 $makefile_path 文件，无法更新 nginx-mod-ubus 模块。" >&2
    fi
}

set_default_theme() {
    local theme="${THEME_SET:-material}"
    local uci_defaults_dir="$BUILD_DIR/files/etc/uci-defaults"
    local theme_script="$uci_defaults_dir/99-default-theme"

    mkdir -p "$uci_defaults_dir"
    cat >"$theme_script" <<EOF
#!/bin/sh
# 首次启动设置默认 LuCI 主题，避免与 iStoreX 冲突。
uci set luci.main.mediaurlbase='/luci-static/${theme}'
uci commit luci
EOF
    chmod +x "$theme_script"
    echo "已注入默认主题 uci-defaults: ${theme}"
}

set_default_lan() {
	# 把 LAN 固定成 192.168.10.x，躲开上级光猫 192.168.1.1
	# 原理：往 base-files 的 uci-defaults 目录塞一个 zzzz- 开头的脚本，
	#       firstboot 时按字母序在 emortal 的 99/zzz-default-settings 之后跑，
	#       于是无论 1.1 是 board 生成的还是 default-settings 写的，都被我们盖掉。
	local d="package/base-files/files/etc/uci-defaults"
	local f="${d}/zzzz-custom-lan"
	mkdir -p "${d}"
	cat > "${f}" <<'EOF'
#!/bin/sh
# auto-generated by set_default_lan : force LAN to 192.168.10.x
uci -q set network.lan.ipaddr='192.168.10.1'
uci -q set network.lan.netmask='255.255.255.0'
uci -q commit network
EOF
	chmod +x "${f}"
	echo "[set_default_lan] wrote ${f}"
}
